apiVersion: apps/v1
kind: Deployment
metadata:
  name: toyproject-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: toyproject
  template:
    metadata:
      labels:
        app: toyproject
    spec:
      containers:
        - name: toyproject
          image: huk27/toyproject:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8090
