apiVersion: v1
kind: Service
metadata:
  name: toyproject-service
spec:
  type: NodePort
  selector:
    app: toyproject
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
      nodePort: 30090
