spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:jinhyy
    username: jinhyy
    password: jinhyy
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug

app:
  kakao:
    host: dapi.kakao.com
    path: /v2/search/blog

  naver:
    host: openapi.naver.com
    path: /v1/search/blog.json